sudo: required
services:
  - docker

before_install:
  - docker build -t  yjorozco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yjorozco/react-test npm test -- --coverage

after_success: 
  - docker build -t yjorozco/multi-client ./client
  - docker build -t yjorozco/multi-nginx ./nginx
  - docker build -t yjorozco/multi-server ./server
  - docker build -t yjorozco/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push yjorozco/multi-client
  - docker push yjorozco/multi-nginx
  - docker push yjorozco/multi-server
  - docker push yjorozco/multi-worker
