sudo: required
services:
  - docker

before_install:
  - docker build -t  yjorozco/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run yjorozco/react-test npm test -- --coverage

after_success: 
  - docker build -f client ./client
  - docker build -f nginx ./nginx
  - docker build -f server ./server
  - docker build -f worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push client
  - docker push nginx
  - docker push server
  - docker push worker
